### ISSUE TITLE
Not working with pagination

### ISSUE THREAD

**Issue by longnt1986** [illuminatech/url-trailing-slash#10]
### What is the expected result?
domain.com/category/category-name/?page=2
### What do you get instead?
domain.com/category/category-name?page=2
### Additional info

| Q                         | A
| ------------------------- | ---
| This Package Version      | 1.1.7
| Laravel Framework Version | 8.6
| PHP version               | 7.4.19
| Operating system          | Windows

**Comment by klimov-paul** [comment]
Unfortunally, this can not be solved via an extension.
The problem is tha Laravel paginators trims the trailing slashes from the URL path at the constructor level:

https://github.com/laravel/framework/blob/v8.74.0/src/Illuminate/Pagination/LengthAwarePaginator.php#L51
https://github.com/laravel/framework/blob/v8.74.0/src/Illuminate/Pagination/CursorPaginator.php#L42

This makes alteration of `Paginator::currentPathResolver()` useless.

Thus you should manually set path for the created paginators using `withPath()` method:

```php
$pagination = User::query()->paginate(5);

$pagination->withPath(URL::current());
```

**Comment by longnt1986** [comment]
I also solved the problem this way.

**Comment by klimov-paul** [comment]
Docs added by commit e1d8969
